// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#define _GNU_SOURCE

#include <openenclave/host.h>
#include <stdio.h>
#include <pthread.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"


oe_enclave_t* enclave = NULL;

pthread_barrier_t barrier;

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

// This is the function that the enclave will call back into to
// print a message.
void host_helloworld()
{
    fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}


void thread_function_1()
{
    pthread_barrier_wait(&barrier);
    printf("hello from the thread_function_1.\n");
    ecall_thread_1(enclave);
}

void thread_function_2()
{
    pthread_barrier_wait(&barrier);
    printf("hello from the thread_function_2.\n");
    ecall_thread_2(enclave);
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;


    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    pthread_barrier_init(&barrier, NULL, 3);

    pthread_t thread_1;
    pthread_create(&thread_1, NULL, thread_function_1, NULL);
    pthread_t thread_2;
    pthread_create(&thread_2, NULL, thread_function_2, NULL);

    pthread_barrier_wait(&barrier);

    // Call into the enclave
    result = enclave_helloworld(enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }


    pthread_join(thread_1, NULL);
    pthread_join(thread_2, NULL);

    pthread_barrier_destroy(&barrier);

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
